### ISSUE TITLE
GET http://localhost:5173/src/main.ts?t=1687424750380 net::ERR_ABORTED 500 (Internal Server Error)

### ISSUE THREAD

**Issue by zdxzheng** [Kitware/vue-vtk-js#7]
GET http://localhost:5173/src/main.ts?t=1687424750380 net::ERR_ABORTED 500 (Internal Server Error)
<vtk-reader vtkClass="vtkOBJReader" :url="url" />
How should the url be set?

**Comment by jourdain** [comment]
What are you talking about? There is no TypeScript in this repo. What URL?
